[package]
name = "malefic-pulse"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
prebuild = []

[target.'cfg(target_os = "windows")'.dependencies]